import { NATIVE_INPUT_MAX_TIMEOUT_MS } from "./native-input.mjs";

const TOOL_SCHEMAS = {
    browser_scan: {
      description: "GA-style web_scan: tabs + simplified content from active tab. Direct MCP default is auto; core web_scan defaults to TMWD user browser.",
      inputSchema: {
        type: "object",
        properties: {
          tabs_only: { type: "boolean", default: false },
          switch_tab_id: { type: "string" },
          session_id: { type: "string" },
          session_url_pattern: { type: "string" },
          tmwd_mode: { type: "string", enum: ["auto", "tmwd", "remote_cdp", "cdp"], default: "auto" },
          tmwd_transport: { type: "string", enum: ["auto", "ws", "link"], default: "auto" },
          tmwd_ws_endpoint: { type: "string" },
          tmwd_link_endpoint: { type: "string" },
          text_only: { type: "boolean", default: false },
          main_only: { type: "boolean", default: false },
          main_only_fallback_to_full: { type: "boolean", default: true },
          main_only_min_chars: { type: "number", minimum: 100, maximum: 10_000 },
          main_only_min_coverage: { type: "number", minimum: 0.05, maximum: 0.95 },
          max_chars: { type: "number", minimum: 1_000, maximum: 300_000 },
          cdp_endpoint: { type: "string" },
        },
      },
  },
  browser_execute_js: {
    description: "GA-style web_execute_js via TMWD bridge commands (cmd=tabs/cookies/cdp/batch) or plain JS. Direct MCP default is auto; core web_execute_js defaults to TMWD user browser.",
    inputSchema: {
      type: "object",
        properties: {
          script: { type: "string" },
          code: { type: "string" },
          tab_id: { type: "string" },
          switch_tab_id: { type: "string" },
          session_id: { type: "string" },
          session_url_pattern: { type: "string" },
          tmwd_mode: { type: "string", enum: ["auto", "tmwd", "remote_cdp", "cdp"], default: "auto" },
          tmwd_transport: { type: "string", enum: ["auto", "ws", "link"], default: "auto" },
          tmwd_ws_endpoint: { type: "string" },
          tmwd_link_endpoint: { type: "string" },
          no_monitor: { type: "boolean", default: false },
          native_auto_fallback: { type: "boolean", default: false },
          native_auto_fallback_policy: {
            type: "string",
            enum: ["strict", "balanced", "aggressive"],
            default: "balanced",
          },
          native_auto_execute: { type: "boolean", default: false },
          native_execute_action_scope: {
            type: "string",
            enum: ["non_pointer", "all"],
            default: "non_pointer",
          },
          native_fallback_action: {
            type: "string",
            enum: [
              "activate_window",
              "move",
              "click",
              "double_click",
              "press",
              "type",
              "paste",
              "scroll",
              "get_window_rect",
            ],
          },
          native_fallback_args: { type: "object" },
          native_fallback_timeout_ms: { type: "number", minimum: 500, maximum: NATIVE_INPUT_MAX_TIMEOUT_MS },
          timeout_ms: { type: "number", minimum: 100, maximum: 120_000 },
          cdp_endpoint: { type: "string" },
          target_url_contains: { type: "string" },
        },
      anyOf: [
        { required: ["script"] },
        { required: ["code"] },
      ],
    },
  },
  browser_extract: {
    description: "Extract actionable nodes from html or active page html.",
    inputSchema: {
      type: "object",
        properties: {
          html: { type: "string" },
          selector_limit: { type: "number", minimum: 1, maximum: 300 },
          tmwd_mode: { type: "string", enum: ["auto", "tmwd", "remote_cdp", "cdp"], default: "auto" },
          tmwd_transport: { type: "string", enum: ["auto", "ws", "link"], default: "auto" },
          tmwd_ws_endpoint: { type: "string" },
          tmwd_link_endpoint: { type: "string" },
          cdp_endpoint: { type: "string" },
          switch_tab_id: { type: "string" },
          session_id: { type: "string" },
          session_url_pattern: { type: "string" },
        },
      },
    },
  browser_diff: {
    description: "Diff two HTML snapshots and return signatures.",
    inputSchema: {
      type: "object",
      properties: {
        before: { type: "string" },
        after: { type: "string" },
      },
      required: ["before", "after"],
    },
  },
  browser_tab_ops: {
    description: "Tab/session operations over the selected browser route (TMWD user browser or explicit remote-debugging CDP).",
    inputSchema: {
      type: "object",
      properties: {
          op: {
            type: "string",
            enum: ["list", "switch", "current", "list_sessions", "find_session", "set_session", "current_session"],
          },
          tab_id: { type: "string" },
          session_id: { type: "string" },
          url_pattern: { type: "string" },
          include_disconnected: { type: "boolean", default: false },
          tmwd_mode: { type: "string", enum: ["auto", "tmwd", "remote_cdp", "cdp"], default: "auto" },
          tmwd_transport: { type: "string", enum: ["auto", "ws", "link"], default: "auto" },
          tmwd_ws_endpoint: { type: "string" },
          tmwd_link_endpoint: { type: "string" },
          cdp_endpoint: { type: "string" },
        },
        required: ["op"],
      },
  },
  browser_native_input: {
    description: "Cross-platform native input fallback (Windows/macOS/Linux) for blocked browser cases.",
    inputSchema: {
      type: "object",
      properties: {
        action: {
          type: "string",
          enum: [
            "activate_window",
            "move",
            "click",
            "double_click",
            "press",
            "type",
            "paste",
            "scroll",
            "get_window_rect",
            "capabilities",
          ],
        },
        x: { type: "number" },
        y: { type: "number" },
        button: { type: "string", enum: ["left", "middle", "right"], default: "left" },
        key: { type: "string" },
        text: { type: "string" },
        delay_ms: { type: "number", minimum: 0, maximum: 10_000 },
        delta_x: { type: "number" },
        delta_y: { type: "number" },
        window_title: { type: "string" },
        window_pid: { type: "number" },
        dry_run: { type: "boolean", default: false },
        timeout_ms: { type: "number", minimum: 500, maximum: NATIVE_INPUT_MAX_TIMEOUT_MS },
      },
      required: ["action"],
    },
  },
};

export { TOOL_SCHEMAS };
