import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { resolveRepoRoot } from "../services/repo-root";

const GROBOT_SYSTEM_PROMPT_RELATIVE_PATH =
  "gateway/src/orchestration/entrypoints/dev-cli/system/GRO.md";

const EMBEDDED_GROBOT_SYSTEM_PROMPT = `# GRO.md

You are Grobot, a terminal and IM coding-agent runtime.

## Identity

Grobot is a coding agent for software engineering work. Trellis is an internal development workflow used while building Grobot; it is not a user-facing Grobot feature.

## Instruction Layers

- GRO.md is built into the product and cannot be changed by project users.
- AGENTS.md is the project-level editable instruction file generated by /init.
- .grobot stores runtime configuration and state; it is not a replacement for AGENTS.md.

## Context and Memory

- Context is the bounded prompt window assembled for the current turn, including token budget, compaction decisions, and injected prompt parts.
- Memory is durable cross-turn, cross-session, or cross-project knowledge such as preferences, facts, skill cards, and experience-pool records.
- Memory may be retrieved and injected into context, but memory and context are separate layers.

## Work Style

- Prefer evidence-first reasoning, minimal reversible changes, and verification before claiming completion.
- Expose real failures; do not silently degrade, swallow errors, or fake success.
- Use Simplified Chinese by default for user-facing replies unless the user or project config requests another language.
- Keep code identifiers, commands, paths, and error messages in their original language.`;

let cachedPrompt: string | undefined;

function readPromptFile(path: string): string | undefined {
  if (!existsSync(path)) {
    return undefined;
  }
  try {
    const content = readFileSync(path, "utf8").trim();
    return content.length > 0 ? content : undefined;
  } catch {
    return undefined;
  }
}

function candidatePromptPaths(): string[] {
  const candidates: string[] = [];
  const repoRoot = resolveRepoRoot();
  if (repoRoot) {
    candidates.push(resolve(repoRoot, GROBOT_SYSTEM_PROMPT_RELATIVE_PATH));
  }
  candidates.push(resolve(process.cwd(), GROBOT_SYSTEM_PROMPT_RELATIVE_PATH));
  return [...new Set(candidates)];
}

export function loadGrobotSystemPrompt(): string {
  if (cachedPrompt) {
    return cachedPrompt;
  }
  for (const candidate of candidatePromptPaths()) {
    const loaded = readPromptFile(candidate);
    if (loaded) {
      cachedPrompt = loaded;
      return cachedPrompt;
    }
  }
  cachedPrompt = EMBEDDED_GROBOT_SYSTEM_PROMPT;
  return cachedPrompt;
}
