#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from evals.ci_label_policy_guard import (  # noqa: E402
    build_policy_result,
    validate_ci_label_policy_config,
    validate_ci_label_policy_file,
)


class CiLabelPolicyGuardTests(unittest.TestCase):
    def _base_config(self) -> dict[str, object]:
        return {
            "schema": "ci_label_policy",
            "schema_version": 1,
            "safe_label_pattern": "^ci\\/[a-z0-9][a-z0-9/_-]{0,49}$",
            "comment_marker": "<!-- harness-gate-summary -->",
            "comment_trigger": {
                "overall_states": ["fail"],
                "trend_severities": ["warn", "error"],
            },
            "comment_template": {
                "title": "### Harness Gate Signal",
                "fields": [
                    {"key": "overall", "label": "overall", "format": "code"},
                    {"key": "action", "label": "action", "format": "text"},
                ],
            },
            "policy_drift": {
                "label_prefix": "ci/policy-drift-",
                "worsening_alert_threshold": 2,
                "worsening_label": "ci/policy-drift-worsening",
                "comment_trigger_severities": ["high", "medium"],
                "action_hints": {
                    "high": "schema mismatch",
                    "medium": "missing fields",
                    "low": "unknown fields",
                    "none": "n/a",
                },
            },
            "managed_label_prefixes": [
                "ci/harness-",
                "ci/owner-",
                "ci/policy-drift-",
                "ci/policy-drift-worsening",
            ],
            "default_color": "6a737d",
            "default_description": "Generated by harness gate automation",
            "label_rules": [
                {
                    "prefix": "ci/harness-pass",
                    "color": "0e8a16",
                    "description": "Harness gate overall state",
                },
                {
                    "prefix": "ci/owner-",
                    "color": "1d76db",
                    "description": "Suggested owner for CI follow-up",
                },
            ],
        }

    def test_repository_policy_is_valid(self) -> None:
        evals_dir = Path(__file__).resolve().parents[1] / "evals"
        policy_file = evals_dir / "ci_label_policy.json"
        config, errors = validate_ci_label_policy_file(policy_file)
        self.assertIsNotNone(config)
        self.assertEqual(errors, [])

    def test_repository_policy_includes_policy_drift_labels(self) -> None:
        evals_dir = Path(__file__).resolve().parents[1] / "evals"
        policy_file = evals_dir / "ci_label_policy.json"
        config, errors = validate_ci_label_policy_file(policy_file)
        self.assertEqual(errors, [])
        self.assertIsNotNone(config)
        assert isinstance(config, dict)
        policy_drift = config.get("policy_drift")
        self.assertIsInstance(policy_drift, dict)
        assert isinstance(policy_drift, dict)
        self.assertEqual(policy_drift.get("label_prefix"), "ci/policy-drift-")
        self.assertEqual(policy_drift.get("worsening_alert_threshold"), 2)
        self.assertEqual(policy_drift.get("worsening_label"), "ci/policy-drift-worsening")
        managed_prefixes = config.get("managed_label_prefixes")
        self.assertIsInstance(managed_prefixes, list)
        assert isinstance(managed_prefixes, list)
        self.assertIn("ci/policy-drift-", managed_prefixes)
        self.assertIn("ci/policy-drift-worsening", managed_prefixes)
        label_rules = config.get("label_rules")
        self.assertIsInstance(label_rules, list)
        assert isinstance(label_rules, list)
        prefixes = {
            rule.get("prefix")
            for rule in label_rules
            if isinstance(rule, dict) and isinstance(rule.get("prefix"), str)
        }
        self.assertTrue(
            {
                "ci/policy-drift-high",
                "ci/policy-drift-medium",
                "ci/policy-drift-low",
                "ci/policy-drift-none",
                "ci/policy-drift-worsening",
            }.issubset(prefixes)
        )

    def test_validate_policy_config_rejects_unknown_fields(self) -> None:
        config = self._base_config()
        config["unexpected"] = True
        errors = validate_ci_label_policy_config(config)
        self.assertTrue(any("unknown fields" in item for item in errors))

    def test_validate_policy_config_rejects_invalid_regex(self) -> None:
        config = self._base_config()
        config["safe_label_pattern"] = "["
        errors = validate_ci_label_policy_config(config)
        self.assertTrue(any("safe_label_pattern is invalid regex" in item for item in errors))

    def test_validate_policy_config_rejects_duplicate_prefix(self) -> None:
        config = self._base_config()
        label_rules = config["label_rules"]
        assert isinstance(label_rules, list)
        label_rules.append(
            {
                "prefix": "ci/owner-",
                "color": "1d76db",
                "description": "dup",
            }
        )
        errors = validate_ci_label_policy_config(config)
        self.assertIn("duplicate label rule prefix: ci/owner-", errors)

    def test_validate_policy_config_rejects_unmanaged_rule_prefix(self) -> None:
        config = self._base_config()
        label_rules = config["label_rules"]
        assert isinstance(label_rules, list)
        label_rules.append(
            {
                "prefix": "ci/trend-",
                "color": "5319e7",
                "description": "trend",
            }
        )
        errors = validate_ci_label_policy_config(config)
        self.assertIn("label_rules[2].prefix is not covered by managed_label_prefixes: ci/trend-", errors)

    def test_validate_policy_config_rejects_unknown_comment_template_field(self) -> None:
        config = self._base_config()
        comment_template = config["comment_template"]
        assert isinstance(comment_template, dict)
        fields = comment_template["fields"]
        assert isinstance(fields, list)
        fields.append({"key": "unknown", "label": "x", "format": "code"})
        errors = validate_ci_label_policy_config(config)
        self.assertTrue(any("comment_template.fields[2].key must be one of" in item for item in errors))

    def test_validate_policy_config_accepts_policy_drift_comment_field(self) -> None:
        config = self._base_config()
        comment_template = config["comment_template"]
        assert isinstance(comment_template, dict)
        fields = comment_template["fields"]
        assert isinstance(fields, list)
        fields.append({"key": "policy_drift", "label": "policy_drift", "format": "code"})
        errors = validate_ci_label_policy_config(config)
        self.assertEqual(errors, [])

    def test_validate_policy_config_rejects_unknown_comment_trigger_severity(self) -> None:
        config = self._base_config()
        comment_trigger = config["comment_trigger"]
        assert isinstance(comment_trigger, dict)
        trend_severities = comment_trigger["trend_severities"]
        assert isinstance(trend_severities, list)
        trend_severities.append("fatal")
        errors = validate_ci_label_policy_config(config)
        self.assertTrue(any("comment_trigger.trend_severities[2] must be one of" in item for item in errors))

    def test_validate_policy_config_rejects_unknown_policy_drift_trigger_severity(self) -> None:
        config = self._base_config()
        policy_drift = config["policy_drift"]
        assert isinstance(policy_drift, dict)
        trigger_severities = policy_drift["comment_trigger_severities"]
        assert isinstance(trigger_severities, list)
        trigger_severities.append("fatal")
        errors = validate_ci_label_policy_config(config)
        self.assertTrue(
            any("policy_drift.comment_trigger_severities[2] must be one of" in item for item in errors)
        )

    def test_validate_policy_config_rejects_unknown_policy_drift_action_hint_key(self) -> None:
        config = self._base_config()
        policy_drift = config["policy_drift"]
        assert isinstance(policy_drift, dict)
        action_hints = policy_drift["action_hints"]
        assert isinstance(action_hints, dict)
        action_hints["fatal"] = "bad"
        errors = validate_ci_label_policy_config(config)
        self.assertIn("policy_drift.action_hints has unknown keys: fatal", errors)

    def test_validate_policy_config_rejects_non_positive_policy_drift_worsening_alert_threshold(self) -> None:
        config = self._base_config()
        policy_drift = config["policy_drift"]
        assert isinstance(policy_drift, dict)
        policy_drift["worsening_alert_threshold"] = 0
        errors = validate_ci_label_policy_config(config)
        self.assertIn("policy_drift.worsening_alert_threshold must be >= 1", errors)

    def test_validate_policy_config_requires_policy_drift_worsening_label_managed(self) -> None:
        config = self._base_config()
        managed_prefixes = config["managed_label_prefixes"]
        assert isinstance(managed_prefixes, list)
        managed_prefixes.remove("ci/policy-drift-worsening")
        errors = validate_ci_label_policy_config(config)
        self.assertIn(
            "policy_drift.worsening_label must be included in managed_label_prefixes: ci/policy-drift-worsening",
            errors,
        )

    def test_validate_policy_config_requires_policy_drift_prefix_managed(self) -> None:
        config = self._base_config()
        managed_prefixes = config["managed_label_prefixes"]
        assert isinstance(managed_prefixes, list)
        managed_prefixes.remove("ci/policy-drift-")
        errors = validate_ci_label_policy_config(config)
        self.assertIn(
            "policy_drift.label_prefix must be included in managed_label_prefixes: ci/policy-drift-",
            errors,
        )

    def test_validate_policy_config_rejects_unknown_comment_trigger_field(self) -> None:
        config = self._base_config()
        comment_trigger = config["comment_trigger"]
        assert isinstance(comment_trigger, dict)
        comment_trigger["unexpected"] = ["x"]
        errors = validate_ci_label_policy_config(config)
        self.assertIn("comment_trigger has unknown fields: unexpected", errors)

    def test_validate_policy_config_rejects_duplicate_comment_trigger_overall_state(self) -> None:
        config = self._base_config()
        comment_trigger = config["comment_trigger"]
        assert isinstance(comment_trigger, dict)
        overall_states = comment_trigger["overall_states"]
        assert isinstance(overall_states, list)
        overall_states.append("fail")
        errors = validate_ci_label_policy_config(config)
        self.assertIn("duplicate comment_trigger.overall_states value: fail", errors)

    def test_validate_policy_config_rejects_duplicate_comment_trigger_severity(self) -> None:
        config = self._base_config()
        comment_trigger = config["comment_trigger"]
        assert isinstance(comment_trigger, dict)
        trend_severities = comment_trigger["trend_severities"]
        assert isinstance(trend_severities, list)
        trend_severities.append("warn")
        errors = validate_ci_label_policy_config(config)
        self.assertIn("duplicate comment_trigger.trend_severities value: warn", errors)

    def test_validate_policy_file_reports_json_error(self) -> None:
        with TemporaryDirectory() as temp_dir:
            policy_file = Path(temp_dir) / "broken.json"
            policy_file.write_text("{not-json", encoding="utf-8")
            config, errors = validate_ci_label_policy_file(policy_file)
            self.assertIsNone(config)
            self.assertTrue(any("Expecting property name enclosed in double quotes" in item for item in errors))

    def test_build_policy_result_includes_hash_and_canonical_payload(self) -> None:
        evals_dir = Path(__file__).resolve().parents[1] / "evals"
        policy_file = evals_dir / "ci_label_policy.json"
        result = build_policy_result(policy_file, include_details=True)
        self.assertTrue(result["ok"], msg=result["errors"])
        self.assertTrue(str(result.get("policy_hash", "")).startswith("sha256:"))
        canonical = result.get("canonical_policy")
        self.assertIsInstance(canonical, dict)
        assert isinstance(canonical, dict)
        self.assertEqual(canonical.get("schema"), "ci_label_policy")
        self.assertEqual(canonical.get("schema_version"), 1)


if __name__ == "__main__":
    unittest.main(verbosity=2)
