import {
  buildFailoverConfig,
  buildProviderPoolConfig,
  buildSingleProviderConfig,
  buildSmokeConfig,
  writeContextEngineGraphAutotuneProjectToml,
  writeContextEngineQualityGuardProjectToml,
  writeContextEngineTrimProjectToml,
  writeExecutionProjectToml,
} from "./config-fixtures.mjs";
import {
  countOccurrences,
  createTempDir,
  hasStartBannerMarker,
  isObject,
  parseJsonObjectSafe,
  readJsonFileSafe,
  readTextFileSafe,
  runCommand,
  runShellScript,
  sanitizePlanSessionSegment,
  sanitizeSessionKey,
  shellEscape,
  stripAnsi,
  writeConfig,
} from "./helpers.mjs";

export function buildStartSmokeFlowContext(repoRoot) {
  return {
    repoRoot,
    createTempDir,
    buildSmokeConfig,
    buildSingleProviderConfig,
    writeExecutionProjectToml,
    writeContextEngineTrimProjectToml,
    writeContextEngineQualityGuardProjectToml,
    writeContextEngineGraphAutotuneProjectToml,
    runCommand,
    runShellScript,
    shellEscape,
    parseJsonObjectSafe,
    isObject,
    readJsonFileSafe,
    readTextFileSafe,
    writeConfig,
    buildFailoverConfig,
    buildProviderPoolConfig,
    stripAnsi,
    hasStartBannerMarker,
    sanitizeSessionKey,
    sanitizePlanSessionSegment,
    countOccurrences,
  };
}
