use crate::models::engine::TurnExecuteInput;
use globset::{Glob, GlobSetBuilder};
use regex::RegexBuilder;
use serde::de::DeserializeOwned;
use serde::Deserialize;
use serde_json::{json, Map, Value};
use std::collections::{HashMap, HashSet, VecDeque};
use std::env;
use std::fs;
use std::io::{BufRead, BufReader, Read, Write};
use std::path::{Path, PathBuf};
use std::process::{Child, ChildStdin, ChildStdout, Command, Stdio};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex, OnceLock};
use std::thread;
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};
use walkdir::WalkDir;

include!("domains/core/mod.rs");
include!("domains/fs/mod.rs");
include!("domains/shell/mod.rs");
include!("domains/mcp/mod.rs");
include!("domains/dispatcher/mod.rs");
include!("domains/tests.rs");
