import type { SurfaceCase } from "./types";

const fullDebugTools = [
  "list",
  "glob",
  "search",
  "read",
  "write",
  "edit",
  "bash",
  "mcp_servers",
  "mcp_call",
  "web_scan",
  "web_execute_js",
  "semantic_search",
  "prompt_enhancer",
  "ask_user",
];

export const surfaceCases: SurfaceCase[] = [
  {
    id: "minimal_read_allowed",
    profile: "minimal",
    advancedToolSchema: false,
    enabledTools: ["read", "edit", "write", "ask_user"],
    modelVisibleTools: ["read", "edit", "write", "ask_user"],
    toolCall: {
      name: "read",
      arguments: {
        path: "notes.txt",
        offset: 1,
        limit: 1,
        include_metadata: true,
      },
    },
    expectedOutcome: "success",
    expectedAssistantMessage: "SURFACE_EXECUTION_OK",
    schemaExpectations: [
      { tool: "read", includes: ["path", "offset", "limit", "include_metadata"], excludes: ["line_start", "pages"] },
      { tool: "ask_user", includes: ["questions"], excludes: ["blocking_node_id", "resume_token"] },
    ],
  },
  {
    id: "coding_rejects_hidden_browser_tool",
    profile: "coding",
    advancedToolSchema: false,
    enabledTools: ["glob", "search", "read", "write", "edit", "bash", "ask_user"],
    modelVisibleTools: ["glob", "search", "read", "write", "edit", "bash", "ask_user"],
    toolCall: {
      name: "web_scan",
      arguments: {
        tabs_only: true,
      },
    },
    expectedOutcome: "error",
    expectedErrorClass: "tool_not_visible",
    expectedErrorData: {
      diagnosticKind: "tool_not_visible",
      tool: "web_scan",
      operation: "validate_tool_visible",
      profile: "coding",
      advancedToolSchema: false,
      recoveryStage: "strategy_switch",
      recommendedNextAction: "switch_tool_strategy",
      recoverable: true,
      recoveryPolicyVersion: "v1",
      visibleToolsIncludes: ["read", "bash"],
      visibleToolsExcludes: ["web_scan"],
      enabledToolsIncludes: ["read", "bash"],
      enabledToolsExcludes: ["web_scan"],
      recoveryHintIncludes: ["model-visible", "current surface"],
    },
    schemaExpectations: [
      { tool: "read", includes: ["path", "line_start", "pages"] },
    ],
  },
  {
    id: "browser_rejects_hidden_execute_transport_args",
    profile: "browser",
    advancedToolSchema: false,
    enabledTools: ["web_scan", "web_execute_js", "read", "ask_user"],
    modelVisibleTools: ["web_scan", "web_execute_js", "read", "ask_user"],
    toolCall: {
      name: "web_execute_js",
      arguments: {
        script: "return 1",
        tmwd_ws_endpoint: "ws://127.0.0.1:9222/devtools/browser/mock",
      },
    },
    expectedOutcome: "error",
    expectedErrorClass: "tool_argument_not_visible",
    expectedErrorData: {
      diagnosticKind: "tool_argument_not_visible",
      tool: "web_execute_js",
      operation: "validate_browser_facade_args_visible",
      profile: "browser",
      advancedToolSchema: false,
      recoveryStage: "strategy_switch",
      recommendedNextAction: "inspect_visible_tool_schema_then_retry",
      recoverable: true,
      recoveryPolicyVersion: "v1",
      backend: "browser-structured",
      mappedTool: "web_execute_js",
      hiddenArgs: ["tmwd_ws_endpoint"],
      visibleArgsIncludes: ["script", "timeout_ms"],
      visibleArgsExcludes: ["tmwd_ws_endpoint", "native_fallback_action"],
      recoveryHintIncludes: ["browser_advanced", "full_debug"],
    },
    schemaExpectations: [
      {
        tool: "web_execute_js",
        includes: ["script", "timeout_ms"],
        excludes: ["tmwd_ws_endpoint", "native_fallback_action"],
      },
      { tool: "read", includes: ["path", "offset", "limit"], excludes: ["line_start", "pages"] },
    ],
  },
  {
    id: "browser_advanced_rejects_full_native_action_args",
    profile: "browser_advanced",
    advancedToolSchema: true,
    enabledTools: ["web_scan", "web_execute_js", "read", "ask_user"],
    modelVisibleTools: ["web_scan", "web_execute_js", "read", "ask_user"],
    toolCall: {
      name: "web_execute_js",
      arguments: {
        script: "return document.title",
        tmwd_ws_endpoint: "ws://127.0.0.1:9222/devtools/browser/mock",
        native_fallback_action: "click",
        native_fallback_args: { x: 1, y: 2 },
      },
    },
    expectedOutcome: "error",
    expectedErrorClass: "tool_argument_not_visible",
    expectedErrorData: {
      diagnosticKind: "tool_argument_not_visible",
      tool: "web_execute_js",
      operation: "validate_browser_facade_args_visible",
      profile: "browser_advanced",
      advancedToolSchema: true,
      recoveryStage: "strategy_switch",
      recommendedNextAction: "inspect_visible_tool_schema_then_retry",
      recoverable: true,
      recoveryPolicyVersion: "v1",
      backend: "browser-structured",
      mappedTool: "web_execute_js",
      hiddenArgs: ["native_fallback_action", "native_fallback_args"],
      visibleArgsIncludes: ["tmwd_ws_endpoint", "native_auto_fallback", "native_fallback_timeout_ms"],
      visibleArgsExcludes: ["native_fallback_action", "native_fallback_args", "native_auto_execute"],
      recoveryHintIncludes: ["browser_advanced", "full_debug"],
    },
    schemaExpectations: [
      {
        tool: "web_execute_js",
        includes: [
          "script",
          "timeout_ms",
          "tmwd_ws_endpoint",
          "target_url_contains",
          "native_auto_fallback",
          "native_auto_fallback_policy",
          "native_fallback_timeout_ms",
        ],
        excludes: [
          "native_auto_execute",
          "native_execute_action_scope",
          "native_fallback_action",
          "native_fallback_args",
        ],
      },
      { tool: "read", includes: ["path", "line_start", "line_end", "pages"] },
    ],
  },
  {
    id: "context_rejects_hidden_semantic_debug_args",
    profile: "context",
    advancedToolSchema: false,
    enabledTools: ["semantic_search", "read", "ask_user"],
    modelVisibleTools: ["semantic_search", "read", "ask_user"],
    toolCall: {
      name: "semantic_search",
      arguments: {
        query: "tool surface drift",
        technical_terms: ["ContextWeaver"],
        bridge_script: "/tmp/custom-contextweaver.mjs",
      },
    },
    expectedOutcome: "error",
    expectedErrorClass: "tool_argument_not_visible",
    expectedErrorData: {
      diagnosticKind: "tool_argument_not_visible",
      tool: "semantic_search",
      operation: "validate_semantic_search_args_visible",
      profile: "context",
      advancedToolSchema: false,
      recoveryStage: "strategy_switch",
      recommendedNextAction: "inspect_visible_tool_schema_then_retry",
      recoverable: true,
      recoveryPolicyVersion: "v1",
      hiddenArgs: ["bridge_script", "technical_terms"],
      visibleArgsIncludes: ["query", "sources", "include_org"],
      visibleArgsExcludes: ["bridge_script", "technical_terms", "timeout_ms"],
      recoveryHintIncludes: ["full_debug"],
    },
    schemaExpectations: [
      {
        tool: "semantic_search",
        includes: ["query", "sources", "per_source_limit", "max_segments", "include_org"],
        excludes: ["technical_terms", "bridge_script", "timeout_ms"],
      },
    ],
  },
  {
    id: "mcp_rejects_hidden_inventory_args",
    profile: "mcp",
    advancedToolSchema: false,
    enabledTools: ["mcp_servers", "mcp_call", "ask_user"],
    modelVisibleTools: ["mcp_servers", "mcp_call", "ask_user"],
    toolCall: {
      name: "mcp_servers",
      arguments: {
        ready_only: true,
        include_disabled: true,
      },
    },
    expectedOutcome: "error",
    expectedErrorClass: "tool_argument_not_visible",
    expectedErrorData: {
      diagnosticKind: "tool_argument_not_visible",
      tool: "mcp_servers",
      operation: "validate_mcp_servers_args_visible",
      profile: "mcp",
      advancedToolSchema: false,
      recoveryStage: "strategy_switch",
      recommendedNextAction: "inspect_visible_tool_schema_then_retry",
      recoverable: true,
      recoveryPolicyVersion: "v1",
      hiddenArgs: ["include_disabled"],
      visibleArgsIncludes: ["ready_only"],
      visibleArgsExcludes: ["include_disabled"],
      recoveryHintIncludes: ["full_debug"],
    },
    schemaExpectations: [
      { tool: "mcp_servers", includes: ["ready_only"], excludes: ["include_disabled"] },
      { tool: "ask_user", includes: ["questions"], excludes: ["blocking_node_id"] },
    ],
  },
  {
    id: "full_debug_allows_full_read_schema",
    profile: "full_debug",
    advancedToolSchema: true,
    enabledTools: fullDebugTools,
    modelVisibleTools: fullDebugTools,
    toolCall: {
      name: "read",
      arguments: {
        path: "notes.txt",
        line_start: 1,
        line_end: 1,
      },
    },
    expectedOutcome: "success",
    expectedAssistantMessage: "SURFACE_EXECUTION_OK",
    schemaExpectations: [
      { tool: "read", includes: ["path", "line_start", "line_end", "pages", "include_metadata"] },
      { tool: "web_execute_js", includes: ["tmwd_ws_endpoint", "native_fallback_action"] },
    ],
  },
];
