export const releaseGateQualityRequiredFragments = [
  "node scripts/lib/runtime-tool-quality-report.mjs",
  "\"$REPORT_PATH\"",
  "\"$RUNTIME_TOOL_DESCRIBE_REPORT_PATH\"",
  "--check-describe-quality",
  "runtime_tool_quality_failed",
] as const;

export const releaseQualityModuleRequiredFragments = [
  "runtimeToolQualitySchemaVersion = 1",
  "export function readRuntimeToolQualityRegistry(",
  "priorityBySurface",
  "actionByReason",
  "reasonByReason",
  "export function pushRuntimeToolQualityFailureReason",
  "export function resolveRuntimeToolQualitySignal(reasons, surface",
  "export function resolveRuntimeToolQualityActionableNextStep",
  "export function runtimeToolQualitySummary(describeSummary, data",
  "export function buildCoreReleaseReport(",
  "export function writeCoreReleaseReport(",
  "const status = failureReasons.length > 0 ? \"fail\" : \"ok\"",
  "const actionSignal = resolveRuntimeToolQualitySignal(failureReasons, \"release\", registry)",
  "actionSignal?.defaultNextStep ?? null",
  "quality_schema_version: runtimeToolQualitySchemaVersion",
  "passed: status === \"ok\"",
  "source: \"runtime_tool_describe\"",
  "failure_reasons: failureReasons",
  "warning_reasons: []",
  "schema_budget_status: schemaBudgetStatus",
  "schema_budget_violations: schemaBudgetViolations",
  "runtime_binary_exists: runtimeBinaryExists",
  "runtime_tool_manifest_match:",
  "runtime_tool_manifest_order_match:",
  "runtime_default_manifest_match:",
  "runtime_default_manifest_order_match:",
  "runtime_only_tools: stringArray(",
  "gateway_only_tools: stringArray(",
  "runtime_default_only_tools: stringArray(",
  "gateway_default_only_tools: stringArray(",
  "runtime_tool_order_mismatch:",
  "runtime_default_order_mismatch:",
  "runtime_schema_profile_summary: recordArray(",
  "runtime_schema_budget_violation_details: recordArray(",
  "surface_execution_smoke_failed",
  "surface_execution_evidence_below_threshold",
  "export function runtimeSurfaceExecutionQualityFailures(",
  "runtime_surface_execution_threshold_status:",
  "runtime_surface_execution_thresholds:",
  "runtime_surface_execution_threshold_failures:",
  "recovery_prompt_quality_failed",
  "export function runtimeRecoveryPromptQualityFailures(",
  "runtime_recovery_prompt_quality_status:",
  "runtime_recovery_prompt_quality_expectations:",
  "runtime_recovery_prompt_quality_failures:",
  "runtime_recovery_feedback_prompt_action_first:",
  "runtime_recovery_feedback_prompt_action_in_catalog:",
  "runtime_recovery_legacy_action_prompt_fallback:",
  "runtime_recovery_feedback_prompt_budget_max_chars:",
  "runtime_recovery_feedback_prompt_budget_within_limit:",
  "runtime_recovery_feedback_prompt_budget_truncated_details:",
  "runtime_recovery_flow_automatic_recovery_denied:",
  "runtime_recovery_flow_guarded_nonrecoverable_bypasses_guard:",
  "runtime_recovery_timeline_legacy_raw_action:",
  "runtime_recovery_timeline_legacy_effective_action:",
  "runtime_surface_execution_smoke_passed:",
  "runtime_surface_execution_profiles_smoked:",
  "runtime_surface_execution_schema_projection_checks:",
  "runtime_surface_execution_structured_error_data_checks:",
  "runtime_surface_execution_recovery_action_catalog_checks:",
  "action_family: actionSignal?.actionFamily ?? \"none\"",
  "action_reason: actionSignal?.reason ?? null",
  "action_required: actionSignal?.actionRequired ?? null",
  "actionable_next_step:",
] as const;

export const statusQualityRequiredFragments = [
  "const RUNTIME_TOOL_QUALITY_SCHEMA_VERSION = 1",
  "type RuntimeToolQualityStatus = \"ok\" | \"warn\" | \"fail\"",
  "type RuntimeToolQualityActionFamily",
  "type RuntimeToolQualityFailureReason",
  "type RuntimeToolQualityWarningReason",
  "type RuntimeToolQualityReason",
  "type RuntimeToolQualityActionRequired",
  "const RUNTIME_TOOL_QUALITY_FAILURE_REASONS",
  "const RUNTIME_TOOL_QUALITY_WARNING_REASONS",
  "interface RuntimeToolQualitySummary",
  "quality_schema_version: typeof RUNTIME_TOOL_QUALITY_SCHEMA_VERSION",
  "status: RuntimeToolQualityStatus",
  "passed: boolean",
  "source: \"status.runtime_tools\"",
  "failure_reasons: RuntimeToolQualityFailureReason[]",
  "warning_reasons: RuntimeToolQualityWarningReason[]",
  "runtime_binary_exists: boolean | null",
  "schema_budget_status: \"passed\" | \"failed\"",
  "schema_budget_violations: number",
  "runtime_describe_source: RuntimeToolEnabledToolsSource",
  "recovery_gate_status: RuntimeToolRecoveryReadinessGateDecision[\"status\"]",
  "action_family: RuntimeToolQualityActionFamily",
  "action_reason: RuntimeToolQualityReason | null",
  "action_required: RuntimeToolQualityActionRequired | null",
  "actionable_next_step: string | null",
  "function resolveRuntimeToolQualityAction",
  "resolveRuntimeToolQualitySignalFromRegistry({",
  "defaultNextStep: signal.defaultNextStep",
  "function resolveRuntimeToolQualityActionableNextStep",
  "const status: RuntimeToolQualityStatus = failReasons.length > 0",
  "passed: status === \"ok\"",
  "quality_schema_version: RUNTIME_TOOL_QUALITY_SCHEMA_VERSION",
  "failure_reasons: failReasons",
  "warning_reasons: warnReasons",
  "schema_budget_status: budgetValidation.ok ? \"passed\" : \"failed\"",
  "action_family: action.actionFamily",
  "action_reason: action.actionReason",
  "action_required: action.actionRequired",
  "actionable_next_step: actionableNextStep",
] as const;

export const releaseFields = [
  "quality_schema_version",
  "status",
  "passed",
  "source",
  "failure_reasons",
  "warning_reasons",
  "schema_budget_status",
  "schema_budget_violations",
  "runtime_binary_exists",
  "runtime_tool_count",
  "runtime_default_enabled_count",
  "runtime_tool_manifest_fingerprint",
  "gateway_tool_manifest_fingerprint",
  "runtime_tool_manifest_match",
  "runtime_tool_manifest_order_match",
  "runtime_default_manifest_match",
  "runtime_default_manifest_order_match",
  "runtime_only_tools",
  "gateway_only_tools",
  "runtime_default_only_tools",
  "gateway_default_only_tools",
  "runtime_tool_order_mismatch",
  "runtime_default_order_mismatch",
  "runtime_schema_profile_summary",
  "runtime_schema_budget_violation_profiles",
  "runtime_schema_budget_violation_details",
  "runtime_surface_execution_smoke_passed",
  "runtime_surface_execution_profiles_smoked",
  "runtime_surface_execution_allowed_workflow_successes",
  "runtime_surface_execution_hidden_tool_rejections",
  "runtime_surface_execution_hidden_arg_rejections",
  "runtime_surface_execution_schema_projection_checks",
  "runtime_surface_execution_structured_error_data_checks",
  "runtime_surface_execution_recovery_action_catalog_checks",
  "runtime_surface_execution_threshold_status",
  "runtime_surface_execution_thresholds",
  "runtime_surface_execution_threshold_failures",
  "runtime_recovery_prompt_quality_status",
  "runtime_recovery_prompt_quality_expectations",
  "runtime_recovery_prompt_quality_failures",
  "runtime_recovery_feedback_prompt_action_first",
  "runtime_recovery_feedback_prompt_action_in_catalog",
  "runtime_recovery_legacy_action_prompt_fallback",
  "runtime_recovery_feedback_prompt_budget_max_chars",
  "runtime_recovery_feedback_prompt_budget_within_limit",
  "runtime_recovery_feedback_prompt_budget_truncated_details",
  "runtime_recovery_flow_automatic_recovery_denied",
  "runtime_recovery_flow_guarded_nonrecoverable_bypasses_guard",
  "runtime_recovery_timeline_legacy_raw_action",
  "runtime_recovery_timeline_legacy_effective_action",
  "action_family",
  "action_reason",
  "action_required",
  "actionable_next_step",
] as const;

export const statusFields = [
  "quality_schema_version",
  "status",
  "passed",
  "source",
  "failure_reasons",
  "warning_reasons",
  "schema_budget_status",
  "schema_budget_violations",
  "runtime_binary_exists",
  "runtime_describe_source",
  "recovery_gate_status",
  "action_family",
  "action_reason",
  "action_required",
  "actionable_next_step",
] as const;
