import type { MemoryOrchestratorPolicySnapshot } from "../orchestrator";
import {
  MEMORY_STRATEGY_AUTOTUNE_STATE_VERSION,
  type MemoryStrategyAutotuneState,
} from "./contract";

export function defaultMemoryStrategyAutotuneState(
  basePolicy: MemoryOrchestratorPolicySnapshot,
): MemoryStrategyAutotuneState {
  return {
    schemaVersion: MEMORY_STRATEGY_AUTOTUNE_STATE_VERSION,
    profile: "general",
    injectBudgetRatio: basePolicy.injectBudgetRatio,
    maxSectionTokens: basePolicy.maxSectionTokens,
    maxGaMemoryRows: basePolicy.maxGaMemoryRows,
    maxTeamExperienceRows: basePolicy.maxTeamExperienceRows,
    minTeamExperienceScore: basePolicy.minTeamExperienceScore,
    adaptiveLearnAlpha: 0.2,
    adaptiveUpdates: 0,
    qualityLowRateEma: 0,
    qualityPressureEma: 0,
    averageUtilizationRatioEma: 0,
    autoLimitTriggeredRateEma: 0,
    snapshotSemanticCompressRateEma: 0,
    hardBudgetRateEma: 0,
    qualityFirstImprovedRateEma: 0,
    hardBudgetFollowupDeltaEma: 0,
    qualityFirstFollowupDeltaEma: 0,
    lastActionDirection: "neutral",
    cooldownTurnsRemaining: 0,
    tightenSignalStreak: 0,
    relaxSignalStreak: 0,
    adaptiveActionScale: 1,
    pendingEvaluationDirection: "neutral",
    pendingEvaluationWarmupTurns: 0,
    pendingBaselineInjectBudgetRatio: basePolicy.injectBudgetRatio,
    pendingBaselineMaxSectionTokens: basePolicy.maxSectionTokens,
    pendingBaselineMaxGaMemoryRows: basePolicy.maxGaMemoryRows,
    pendingBaselineMaxTeamExperienceRows: basePolicy.maxTeamExperienceRows,
    pendingBaselineMinTeamExperienceScore: basePolicy.minTeamExperienceScore,
    pendingBaselineQualityLowRateEma: 0,
    pendingBaselineQualityPressureEma: 0,
    pendingBaselineAverageUtilizationRatioEma: 0,
    pendingBaselineAutoLimitTriggeredRateEma: 0,
    pendingBaselineSnapshotSemanticCompressRateEma: 0,
    pendingBaselineHardBudgetFollowupDeltaEma: 0,
    pendingBaselineQualityFirstFollowupDeltaEma: 0,
    pendingBaselineQualityFirstImprovedRateEma: 0,
    outcomeConfidenceEma: 0,
    lastOutcomeGain: 0,
    outcomeRollbackCount: 0,
    outcomeNegativeStreak: 0,
    lastReason: "bootstrap",
    updatedAt: null,
  };
}
